### ISSUE TITLE
Roadmap for v0.5.x

### ISSUE THREAD

**Issue by PENGUINLIONG** [PENGUINLIONG/spirq-rs#54]
Just a todo list for future development.

- [x] Deprecate poorly designed APIs
- [x] Separate pipeline procedures and error
- [ ] `no_std`
- [ ] Compile to WASM
- [x] Raytracing pipeline
- [x] Mesh pipeline
